// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAfTq3K_Bj4uK64PpO3A58t0-o8ZY9LkY',
    appId: '1:311562656802:android:a7fa4870a9d2bb59a8be7b',
    messagingSenderId: '311562656802',
    projectId: 'xogame-project',
    authDomain: 'xogame-project.firebaseapp.com',
    storageBucket: 'xogame-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAfTq3K_Bj4uK64PpO3A58t0-o8ZY9LkY',
    appId: '1:311562656802:android:a7fa4870a9d2bb59a8be7b',
    messagingSenderId: '311562656802',
    projectId: 'xogame-project',
    storageBucket: 'xogame-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-um1Sq_5uGVuEVdUgqzCYaUgKEniClQ',
    appId: '1:311562656802:ios:9a39163ec93f1721a8be7b',
    messagingSenderId: '311562656802',
    projectId: 'xogame-project',
    storageBucket: 'xogame-project.appspot.com',
    iosBundleId: 'com.example.xoGame',
  );
}
